### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by hynek** [dropbox/pytest-flakefinder#3]
Hi,

could you please put your useful plugin on PyPI?  It’s [not hard](https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/) and helps a lot.

Thanks!

**Comment by euresti** [comment]
Done!
https://pypi.python.org/pypi/pytest-flakefinder
Thanks!

**Comment by adaamz** [comment]
would be nice if this is in readme
